sudo: required
services:
  - docker
before_install:
  - docker build -t krauty/demo-project -f Dockerfile.dev .

script:
  - docker run krauty/demo-project npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-tut
  env: DockerTut-env
  bucket_name: elasticbeanstalk-us-east-2-637501083051
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"